server:
  port: 0

eureka:
  instance:
    leaseRenewalIntervalSeconds: 10
    instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${random.value}}}
  client:
    registryFetchIntervalSeconds: 5
 
info:
  service: ${spring.application.name}
  ip: ${spring.cloud.client.hostname}
  port: ${local.server.port}